### PR TITLE
Fix cancel and lookup with arrays

### PR DESCRIPTION
**Pull request by fdbatista**
These two commits should fix these minor bugs in the code.
I need to use both functions ASAP, so it would be great if you could review these changes.
Thanks :)

### CODE REVIEW

**Comment by fdbatista** [comment]
@julyanserra Good day. I've created this PR to fix a couple things I found. Could you please take a look at it? Thanks.

**Comment by domix** [comment]
hi @fdbatista, thank you very much for your contribution, really appreciate it, thanks!

Before we can merge this PR, please provide some evidence that your fix is working as expected. Once we have some evidence we can safely merge this PR.

Keep making crypto useful!

**Review by fdbatista — COMMENTED** [review]
@domix I will upload some screenshots as evidence of what happens with the original code and with my proposal.

**Invoking _lookup_order_ with original code**: as you can see, the method receives an array composed by 3 ids and the method merges it in a single string without delimiter, because the `implode` function has an empty `glue` parameter.
image

Obviously, I am getting an exception after invoking the method:
image

Finally, this is what happens when I invoke the method after applying my suggested change:
image

The code runs as expected and I get the details for all three orders in the response payload.

**Comment by fdbatista** [comment]
@domix I will upload some screenshots as evidence of what happens with the original code and with my proposal.

**Invoking _cancel_order_ with original code**: I am getting an exception after invoking the method when it receives at least one oid (if you pass the word `all` it works fine):

image

This is what happens when I invoke the method after applying my suggested change:

image

The code runs as expected and I get the ID for the cancelled order(s) in the response payload.

**Review by domix — APPROVED** [review]
LGTM

Thank you!

**Comment by fdbatista** [comment]
> LGTM
> 
> Thank you!

Great! Thank you

**Comment by fdbatista** [comment]
@domix I changed my composer.json file for installing `dev-master` instead of version 1.2, but for some reason composer keeps downloading the old code without the fixes. Any idea why? Do you have to release a new version?

**Comment by domix** [comment]
oh yes, let me ask someone else in the team to publish the new version

**Pull request merged**
